# Slicing


In [1]:
import numpy as np
l=np.array([[23,25,27,29],[43,45,47,49],[62,64,66,68]])

In [2]:
l=np.array([[23,25,27,29],[43,45,47,49],[62,64,66,68]])
print(l)

[[23 25 27 29]
 [43 45 47 49]
 [62 64 66 68]]


In [3]:
print(l,"\n")
print(l[0,1],"\n")
print(l[1,2],"\n")
print(l[2,1],"\n")
print(l[0:2,1],"\n")
print(l[1,0:2],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")
print(l[0:2,-1],"\n")
print(l[-1,-1],"\n")
print(l[-2,-1],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 64 66 68]] 

25 

47 

64 

[25 45] 

[43 45] 

[62 64 66 68] 

[62 64] 

[29 49] 

68 

49 



# Stacking

In [4]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
e=np.arange(12,24).reshape(3,4)
print(e,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



In [5]:
print(d,"\n")
print(e,"\n")
print(np.hstack((d,e)),"\n")
print(np.hstack((e,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [6]:
print(d,"\n")
print(e,"\n")
print(np.vstack((d,e)),"\n")
print(np.vstack((e,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [7]:
from numpy import random

In [8]:
x=random.randint(100)
print(x)

79


In [9]:
x=random.rand()
print(x)

0.33323327328953645


In [10]:
x=random.randint(100)
print(x)

38
