In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[7,8,9,10]])
print(arr)

[[ 1  2  3  4]
 [ 7  8  9 10]]


In [3]:
arr.shape

(2, 4)

In [4]:
arr.size

8

In [5]:
arr.ndim

2

In [6]:
arr.min
arr.max

<function ndarray.max>

In [7]:
arr.min


<function ndarray.min>

In [8]:
arr.dtype


dtype('int32')

In [9]:
x = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(x,"\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]] 



In [10]:
x = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.float64)
print(x,"\n")
print(x.dtype,"\n")
print(x.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [11]:
x.size

9

In [12]:
y = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.complex128)
print(y,"\n")
print(y.dtype,"\n")
print(y.itemsize)

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16


In [13]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.complex64)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize)

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8


In [14]:
a = np.array([[20,21,22],[25,26,27],[30,31,32]],dtype=np.int32)
print(a,"\n")
print(a.dtype,"\n")
print(a.itemsize)

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

int32 

4


In [15]:
y.dtype

dtype('complex128')

In [16]:
print(y.dtype)

complex128


In [17]:
x.sum

<function ndarray.sum>

In [18]:
print(x.sum)

<built-in method sum of numpy.ndarray object at 0x0000007B454EA330>


In [19]:
print(np.sum(x))

234.0


In [20]:
print(np.sum(z))

(234+0j)


In [21]:
print(np.sum(a))

234


In [22]:
print(np.sum(y))

(234+0j)


In [23]:
a.dtype
x.dtype
y.dtype
z.dtype

dtype('complex64')

In [24]:
print(a.dtype,x.dtype,y.dtype,z.dtype)

int32 float64 complex128 complex64


In [25]:
print(x,"\n")
print(np.min(x),"\n")
print(np.min(x, axis=0))
print(np.min(x, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

20.0 

[20. 21. 22.]
[20. 25. 30.]


In [26]:
print(x,"\n")
print(np.max(x),"\n")
print(np.max(x, axis=0))
print(np.max(x, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

32.0 

[30. 31. 32.]
[22. 27. 32.]


In [27]:
print(x,"\n")
print(np.mean(x),"\n")
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))
print("\n")
print(x,"\n")
print(np.median(x),"\n")
print(np.median(x, axis=0))
print(np.median(x, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

26.0 

[25. 26. 27.]
[21. 26. 31.]


[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

26.0 

[25. 26. 27.]
[21. 26. 31.]


In [28]:
print(x,"\n")
print(np.std(x),"\n")
print(np.std(x, axis=0))
print(np.std(x, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

4.163331998932265 

[4.0824829 4.0824829 4.0824829]
[0.81649658 0.81649658 0.81649658]


In [29]:
print(arr,"\n")
print(np.std(arr),"\n")
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

[[ 1  2  3  4]
 [ 7  8  9 10]] 

3.2015621187164243 

[3. 3. 3. 3.]
[1.11803399 1.11803399]


In [30]:
print(x,"\n")
print(np.var(x),"\n")
print(np.var(x, axis=0))
print(np.var(x, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

17.333333333333332 

[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]


In [31]:
print(a,"\n")
print(np.ptp(a),"\n")
print(np.ptp(a, axis=0))
print(np.ptp(a, axis=1))

[[20 21 22]
 [25 26 27]
 [30 31 32]] 

12 

[10 10 10]
[2 2 2]
